stages:
  - install
  - build
  - deploy_dev
  - deploy_prod

cache:
  key: ${CI_BUILD_REF_NAME}
  paths:
    - node_modules/
    - dist/

# 安装依赖
npm_install:
  stage: install
  only:
    - dev
    - master
  script:
    - npm install

# 构建项目
build:
  stage: build
  only:
    - dev
    - master
  script:
    - npm run build

deploy_dev:
  stage: deploy_dev
  only:
    - dev
  script:
    - /bin/cp -rf ./dist/* /data/docker/nginx/www/chirp

deploy_prod:
  stage: deploy_prod
  only:
    - master
  script:
    - mv dist chirp
    - scp -i /data/.ssh/onepro_prod.pem -r ./chirp ec2-user@34.197.131.40:/home/ec2-user/dists
