// 获取登录用户的信息
export const USER_INFO_PENDING = 'USER_INFO_PENDING'
export const USER_INFO_FULFILLED = 'USER_INFO_FULFILLED'
export const USER_INFO_REJECTED = 'USER_INFO_REJECTED'

// 获取用户创建的 Clients 的信息
export const CLIENTS_INFO_PENDING = 'CLIENTS_INFO_PENDING'
export const CLIENTS_INFO_FULFILLED = 'CLIENTS_INFO_FULFILLED'
export const CLIENTS_INFO_REJECTED = 'CLIENTS_INFO_REJECTED'

// 获取用户的所有 Works 的信息
export const WORKS_INFO_PENDING = 'WORKS_INFO_PENDING'
export const WORKS_INFO_FULFILLED = 'WORKS_INFO_FULFILLED'
export const WORKS_INFO_REJECTED = 'WORKS_INFO_REJECTED'

// 获取登录所有员工用户的信息
export const STAFFS_INFO_PENDING = 'STAFFS_INFO_PENDING'
export const STAFFS_INFO_FULFILLED = 'STAFFS_INFO_FULFILLED'
export const STAFFS_INFO_REJECTED = 'STAFFS_INFO_REJECTED'

// Invoice
// 获取用户的所有 Invoices 的信息
export const INVOICES_INFO_PENDING = 'INVOICES_INFO_PENDING'
export const INVOICES_INFO_FULFILLED = 'INVOICES_INFO_FULFILLED'
export const INVOICES_INFO_REJECTED = 'INVOICES_INFO_REJECTED'

// Invoice
// 获取用户的所有Clients的所有 Invoices 的信息
export const ALL_INVOICES_INFO_PENDING = 'INVOICES_INFO_PENDING'
export const ALL_INVOICES_INFO_FULFILLED = 'INVOICES_INFO_FULFILLED'
export const ALL_INVOICES_INFO_REJECTED = 'INVOICES_INFO_REJECTED'

// Create/Modify Invoice
export const INVOICE_NOT_INVOICED_WORKS_PENDING = 'INVOICE_NOT_INVOICED_WORKS_PENDING'
export const INVOICE_NOT_INVOICED_WORKS_UPDATE = 'INVOICE_NOT_INVOICED_WORKS_UPDATE'
export const INVOICE_NOT_INVOICED_WORKS_REJECTED = 'INVOICE_NOT_INVOICED_WORKS_REJECTED'

// Modify Invoice
export const INVOICE_INVOICED_WORKS_PENDING = 'INVOICE_INVOICED_WORKS_PENDING'
export const INVOICE_INVOICED_WORKS_UPDATE = 'INVOICE_INVOICED_WORKS_UPDATE'
export const INVOICE_INVOICED_WORKS_REJECTED = 'INVOICE_INVOICED_WORKS_REJECTED'

// Fetch 失败的信息
export const FETCH_ERROR = 'FETCH_ERROR'

// 获取用户相关的 chirps 的信息
export const CHIRPS_INFO_PENDING = 'CHIRPS_INFO_PENDING'
export const CHIRPS_INFO_FULFILLED = 'CHIRPS_INFO_FULFILLED'
export const CHIRPS_INFO_REJECTED = 'CHIRPS_INFO_REJECTED'

export const CURRENT_CHIRP_PENDING ='CURRENT_CHIRP_PENDING'
export const CURRENT_CHIRP_FULFILLED ='CURRENT_CHIRP_FULFILLED'
export const CURRENT_CHIRP_REJECTED ='CURRENT_CHIRP_REJECTED'

export const SET_CHIRP_PENDING ='SET_CHIRP_PENDING'
export const SET_CHIRP_FULFILLED ='SET_CHIRP_FULFILLED'
export const SET_CHIRP_REJECTED ='SET_CHIRP_REJECTED'

export const SEND_MSG_PENDING = 'SEND_MSG_PENDING'
export const SEND_MSG_FULFILLED = 'SEND_MSG_FULFILLED'
export const SEND_MSG_REJECTED = 'SEND_MSG_REJECTED'

export const SEND_MSG_SUCCESS_PENDING = 'SEND_MSG_SUCCESS_PENDING'
export const SEND_MSG_SUCCESS_FULFILLED = 'SEND_MSG_SUCCESS_FULFILLED'
export const SEND_MSG_SUCCESS_REJECTED = 'SEND_MSG_SUCCESS_REJECTED'
