// 获取登录用户的信息
export const USER_INFO_PENDING = 'USER_INFO_PENDING'
export const USER_INFO_FULFILLED = 'USER_INFO_FULFILLED'
export const USER_INFO_REJECTED = 'USER_INFO_REJECTED'





// 获取用户相关的 chirps 的信息
export const CHIRPS_INFO_PENDING = 'CHIRPS_INFO_PENDING'
export const CHIRPS_INFO_FULFILLED = 'CHIRPS_INFO_FULFILLED'
export const CHIRPS_INFO_REJECTED = 'CHIRPS_INFO_REJECTED'

export const CURRENT_CHIRP_PENDING ='CURRENT_CHIRP_PENDING'
export const CURRENT_CHIRP_FULFILLED ='CURRENT_CHIRP_FULFILLED'
export const CURRENT_CHIRP_REJECTED ='CURRENT_CHIRP_REJECTED'

export const SET_CHIRP_PENDING ='SET_CHIRP_PENDING'
export const SET_CHIRP_FULFILLED ='SET_CHIRP_FULFILLED'
export const SET_CHIRP_REJECTED ='SET_CHIRP_REJECTED'

export const SEND_MSG_PENDING = 'SEND_MSG_PENDING'
export const SEND_MSG_FULFILLED = 'SEND_MSG_FULFILLED'
export const SEND_MSG_REJECTED = 'SEND_MSG_REJECTED'

export const SEND_MSG_SUCCESS_PENDING = 'SEND_MSG_SUCCESS_PENDING'
export const SEND_MSG_SUCCESS_FULFILLED = 'SEND_MSG_SUCCESS_FULFILLED'
export const SEND_MSG_SUCCESS_REJECTED = 'SEND_MSG_SUCCESS_REJECTED'


export const CREATE_CHIRP = 'CREATE_CHIRP'
export const DELETE_CHIRP_PENDING = 'DELETE_CHIRP_PENDING'
export const DELETE_CHIRP_FULFILLED = 'DELETE_CHIRP_FULFILLED'
export const DELETE_CHIRP_REJECTED = 'DELETE_CHIRP_REJECTED'


//历史消息
export const HISTORY_MESSAGE_PENDING = 'HISTORY_MESSAGE_PENDING'
export const HISTORY_MESSAGE_FULFILLED = 'HISTORY_MESSAGE_FULFILLED'
export const HISTORY_MESSAGE_REJECTED = 'HISTORY_MESSAGE_REJECTED'

//发送图片
export const SEND_IMG_PENDING = 'SEND_IMG_PENDING'
export const SEND_IMG_FULFILLED = 'SEND_IMG_FULFILLED'
export const SEND_IMG_REJECTED = 'SEND_IMG_REJECTED'

//追加图片
export const APPEND_IMG_PENDING = 'APPEND_IMG_PENDING'
export const APPEND_IMG_FULFILLED = 'APPEND_IMG_FULFILLED'
export const APPEND_IMG_REJECTED = 'APPEND_IMG_REJECTED'

//发送文件
export const SEND_FILE_PENDING = 'SEND_FILE_PENDING'
export const SEND_FILE_FULFILLED = 'SEND_FILE_FULFILLED'
export const SEND_FILE_REJECTED = 'SEND_FILE_REJECTED'
//更新chirp设置
export const UPDATE_CHIRP_SETTING = 'UPDATE_CHIRP_SETTING'
