//登录操作
export const LOGIN_PENDING = 'LOGIN_PENDING'
export const LOGIN_FULFILLED = 'LOGIN_FULFILLED'
export const LOGIN_REJECTED = 'LOGIN_REJECTED'

//匿名用户登录
export const ANONYMOUS_LOGIN_PENDING = 'ANONYMOUS_LOGIN_PENDING'
export const ANONYMOUS_LOGIN_FULFILLED = 'ANONYMOUS_LOGIN_FULFILLED'
export const ANONYMOUS_LOGIN_REJECTED = 'ANONYMOUS_LOGIN_REJECTED'

// 获取登录用户的信息
export const USER_INFO_PENDING = 'USER_INFO_PENDING'
export const USER_INFO_FULFILLED = 'USER_INFO_FULFILLED'
export const USER_INFO_REJECTED = 'USER_INFO_REJECTED'
//用户登出
export const LOGOUT = 'LOGOUT'
//更新用户信息
export const UPDATE_USER = 'UPDATE_USER'
